AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable
  SuggestExtensions: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
